name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache NPM modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm
      - name: Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
